/* eslint-disable quote-props */
/**
 * Traducciones en español para los textos heredados del editor original.
 *
 * El proyecto de origen guarda cada traducción junto a su texto. Mantener aquí
 * la capa española permite ofrecer una traducción completa sin alterar cientos
 * de descriptores XML y facilita revisar la terminología del juego en un solo sitio.
 */
const SPANISH_TRANSLATIONS: Record<string, string> = {
	'A new version of the program is available': 'Hay una nueva versión disponible',
	'A new version of the program is available.': 'Hay una nueva versión disponible.',
	'Add': 'Añadir',
	'Add to Favorites': 'Añadir a favoritos',
	'Added': 'Añadidos',
	'Additionally': 'Opciones adicionales',
	'Addons found': 'Complementos encontrados',
	'Advanced Mode': 'Modo avanzado',
	'All': 'Todos',
	'Always': 'Siempre',
	'ANK MK38': 'ANK MK38',
	'Attention!': '¡Atención!',
	'Available': 'Disponible',
	'Available wheel sizes': 'Tamaños de rueda disponibles',
	'AWD consumption modifier': 'Modificador de consumo con tracción total',
	'Back steer speed': 'Velocidad de retorno de la dirección',
	'Backup': 'Copia de seguridad',
	'Bandit banana': 'Grúa del Bandit',
	'Basic': 'Juego base',
	'Basic fuel consumption of the gearbox': 'Consumo base de combustible de la caja de cambios',
	'Battery': 'Batería',
	'Before removing the crane, be sure to remove it from the truck.': 'Antes de quitar la grúa de los archivos, desmóntala del camión dentro del juego.',
	'Body friction': 'Agarre fuera de carretera',
	'Body friction asphalt': 'Agarre en asfalto',
	'Braking delay': 'Retardo de frenado',
	'By rank': 'Por rango',
	'Can the winch work with the engine turned off': 'Permite usar el cabrestante con el motor apagado',
	'Cancel': 'Cancelar',
	'Cargo quantity': 'Espacios de carga',
	'Center of mass offset': 'Desplazamiento del centro de masa',
	'Central Asia': 'Asia Central',
	'Change': 'Gestionar',
	'Changed': 'Modificados',
	'Checking admin privileges': 'Comprobando permisos de administrador',
	'Checking files': 'Comprobando archivos',
	'Checking initial.pak': 'Comprobando initial.pak',
	'Close': 'Cerrar',
	'Completed': 'Completado',
	'Configuration exported successfully': 'La configuración se exportó correctamente',
	'Control': 'Control',
	'Conventional trailers': 'Remolques para camión',
	'Country': 'Región',
	'crane': 'grúa',
	'Cranes': 'Grúas',
	'Critical damage threshold': 'Umbral de daño crítico',
	'Damage capacity': 'Resistencia al daño',
	'Damage consumption modifier': 'Aumento de consumo por daño',
	'Damaged max torque modifier': 'Potencia con daño máximo',
	'Damaged min torque modifier': 'Potencia al alcanzar daño crítico',
	'Damping': 'Amortiguación',
	'Default: {}': 'Valor original: {}',
	'Defined by the addon': 'Definido por el complemento',
	'Delay after pressing "turn on the engine"': 'Tiempo que tarda el motor en arrancar después de pulsar el botón',
	'Delete': 'Quitar',
	'Delete from favorites': 'Quitar de favoritos',
	'Description': 'Descripción',
	'Description of the item': 'Texto descriptivo que se muestra dentro del juego',
	'Differential lock': 'Bloqueo de diferencial',
	'DLC': 'DLC',
	'DLC folder not found': 'No se encontró la carpeta de los DLC',
	'Do you really want to reset all the parameters to the original ones?': '¿Quieres restablecer todos los parámetros a sus valores originales?',
	'Does the item / truck unlock using location search': 'Indica si el objeto o camión se desbloquea al encontrarlo en el mapa',
	'Does the wheel have good grip on ice': 'Indica si el neumático tiene buen agarre sobre hielo',
	'Downloading': 'Descargando',
	'Drive': 'Tracción',
	'Driven': 'Con tracción',
	'Driving with AWD': 'Con tracción al activar AWD',
	'Edit DLC': 'Editar contenido DLC',
	'Edit Modifications': 'Usar modificaciones',
	'Edited': 'Editados',
	'Engine': 'Motor',
	'Engine power': 'Potencia del motor',
	'Engine responsiveness (revving speed)': 'Rapidez con la que el motor sube de revoluciones',
	'Engine start delay': 'Retardo de arranque',
	'Engines': 'Motores',
	'Error': 'Error',
	'Exhaust start time': 'Inicio del escape',
	'Exit': 'Salir',
	'Export': 'Exportar',
	'Export error': 'Error al exportar',
	'Exported': 'Exportado',
	'Extra': 'Extras',
	'Extra wheel': 'Rueda adicional',
	'Extract only certain files from DLC': 'Extrae solo los archivos necesarios de los DLC para acelerar la carga',
	'Failed to load file. Most likely there is an error in the file.': 'No se pudo cargar el archivo. Es probable que contenga un error.',
	'Failed to update files in initial. pak. There is no access to the record': 'No se pudo actualizar initial.pak porque el archivo no permite escritura.',
	'Favorites': 'Favoritos',
	'File': 'Archivo',
	'Files': 'Archivos relacionados',
	'Filter by name': 'Buscar por nombre',
	'Find on map': 'Encontrar en el mapa',
	'Folder classes not found': 'No se encontró la carpeta classes',
	'Found': 'Encontrados',
	'Friction with mud': 'Agarre del neumático en barro',
	'Friction with the ground, without dirt and other objects': 'Agarre del neumático sobre tierra firme y superficies sin barro',
	'Friction with the road': 'Agarre del neumático sobre asfalto',
	'Front suspension': 'Suspensión delantera',
	'Fuel': 'Combustible',
	'Fuel capacity': 'Capacidad de combustible',
	'Fuel consumption': 'Consumo de combustible',
	'Fuel consumption multiplier in this gear': 'Multiplicador de consumo de combustible en esta marcha',
	'Fuel consumption multiplier when the car is stationary with the engine running': 'Multiplicador de consumo cuando el vehículo está detenido con el motor encendido',
	'Fuel mass': 'Masa del combustible',
	'Fuel modifier': 'Modificador de consumo',
	'Game data': 'Archivos del juego',
	'Game folder': 'Carpeta del juego',
	'Gearbox': 'Caja de cambios',
	'Gearboxes': 'Cajas de cambios',
	'Gears': 'Marchas',
	'Gears availability': 'Marchas disponibles',
	'Github': 'GitHub',
	'Green zone: {}': 'Zona verde: {}',
	'Heavy': 'Pesado',
	'Heavy duty': 'Trabajo pesado',
	'Height': 'Altura',
	'Help': 'Ayuda',
	'High': 'Alta',
	'Highway': 'Carretera',
	'How to use': 'Guía de uso',
	'IDLE fuel consumption': 'Consumo al ralentí',
	'Ignore': 'Ignorar',
	'Import': 'Importar',
	'Initial setup of the program': 'Configuración inicial',
	'initial.pak not found': 'No se encontró initial.pak',
	'Initial.pak update detected, apply previous changes?': 'Se detectó una actualización de initial.pak. ¿Quieres volver a aplicar tus cambios?',
	'initial.pak was successfully restored.': 'initial.pak se restauró correctamente.',
	'Installed': 'Instalado',
	'Installer (.exe)': 'Instalador (.exe)',
	'Invalid initial.pak selected': 'El archivo seleccionado no es un initial.pak válido',
	'Is a manual gear available': 'Indica si está disponible el ajuste manual preciso',
	'Is high gear available': 'Indica si está disponible la marcha alta',
	'Is lower gear available (45% of the first gear speed)': 'Indica si está disponible la marcha baja (45 % de la velocidad de primera)',
	'Is lower- available (20% of the first gear speed)': 'Indica si está disponible Baja- (20 % de la velocidad de primera)',
	'Is lower+ (first) gear available': 'Indica si está disponible Baja+ (velocidad de primera)',
	'Length': 'Longitud',
	'List of trailers': 'Remolques',
	'List of trucks': 'Vehículos',
	'Load': 'Cargar',
	'Loading': 'Cargando',
	'Loading DLC': 'Cargando DLC',
	'Loading game texts': 'Cargando textos del juego',
	'Loading mods': 'Cargando modificaciones',
	'Lower': 'Baja',
	'Lower-': 'Baja-',
	'Lower+': 'Baja+',
	'Main': 'Archivo principal',
	'Mass': 'Masa',
	'Max angular velocity delta': 'Aceleración angular máxima',
	'Max wheel angular velocity': 'Velocidad angular máxima de la rueda',
	'Maximum length of the winch rope': 'Longitud máxima del cable del cabrestante',
	'Maximum suspension height': 'Altura máxima de la suspensión',
	'Maximum suspension travel (The position that the wheel can take if the suspension is in working condition and its stiffness is zero when the wheel is hanging in the air)': 'Recorrido máximo de la suspensión cuando la rueda queda en el aire y la suspensión no ejerce fuerza',
	'Maximum: {}': 'Máximo: {}',
	'Middle suspension': 'Suspensión central',
	'Minimum suspension height': 'Altura mínima de la suspensión',
	'Minimum suspension height in broken condition': 'Altura mínima con la suspensión averiada',
	'Minimum suspension stroke (The position that the wheel can take when the suspension is fully sagged)': 'Recorrido mínimo cuando la suspensión está totalmente comprimida',
	'Minimum: {}': 'Mínimo: {}',
	'Modifications': 'Modificaciones',
	'Name': 'Nombre',
	'Name of the item': 'Nombre del objeto dentro del juego',
	'Next': 'Continuar',
	'No': 'No',
	'None': 'Ninguno',
	'Northern Europe': 'Europa del Norte',
	'Not Available': 'No disponible',
	'Number of cargo slots': 'Cantidad de espacios disponibles para carga',
	'Offroad': 'Todoterreno',
	'Ok': 'Aceptar',
	'Open': 'Abrir',
	'Open file': 'Abrir archivo',
	'Open Files': 'Abrir carpeta de trabajo',
	'Optimize unpacking': 'Optimizar la extracción',
	'Other': 'Otros',
	'Parameters cannot be imported. No parameters found for %file.': 'No se pueden importar los parámetros: no se encontraron datos para %file.',
	'Parameters have been reset': 'Los parámetros se restablecieron',
	'Portable (.rar)': 'Versión portátil (.rar)',
	'Power multiplier when engine damage has reached the breakdown threshold': 'Multiplicador de potencia cuando el motor alcanza el umbral de avería',
	'Power multiplier when the engine is close to complete breakdown (to 0 strength)': 'Multiplicador de potencia cuando el motor está cerca de romperse por completo',
	'Precise adjustment': 'Ajuste preciso',
	'Price': 'Precio',
	'Processing': 'Procesando',
	'Program language': 'Idioma de la aplicación',
	'Rear suspension': 'Suspensión trasera',
	'Recovery': 'Recuperación',
	'Red zone: {}': 'Zona roja: {}',
	'Reducing the speed and intensity of vibrations': 'Reduce la velocidad y la intensidad de las oscilaciones',
	'Repairs': 'Reparaciones',
	'Repairs capacity': 'Puntos de reparación',
	'Reset': 'Restablecer',
	'Responsiveness': 'Respuesta',
	'Restore': 'Restaurar',
	'Reverse': 'Marcha atrás',
	'Rides on ice': 'Agarre en hielo',
	'Russia': 'Rusia',
	'Save': 'Guardar',
	'Saved': 'Cambios guardados',
	'Saving...': 'Guardando...',
	'Scout': 'Explorador',
	'Scout trailers': 'Remolques de explorador',
	'Select .pak': 'Elegir archivo .pak',
	'Select folder': 'Elegir carpeta del juego',
	'Set of wheels': 'Conjunto de ruedas',
	'Settings': 'Ajustes',
	'Startup error. The program must be run as an administrator.': 'No se pudo iniciar. Ejecuta la aplicación como administrador.',
	'Steer speed': 'Velocidad de giro',
	'Steering angle': 'Ángulo de dirección',
	'Steering sensitivity': 'Sensibilidad de la dirección',
	'Steering wheel rotation speed': 'Velocidad a la que giran las ruedas al dirigir el vehículo',
	'Steering wheel sensitivity': 'Sensibilidad del volante',
	'Strength': 'Fuerza',
	'Substance friction': 'Agarre en barro',
	'Support': 'Apoyar el proyecto original',
	'Suspension': 'Suspensión',
	'Suspension Critical Damage Threshold': 'Nivel a partir del cual la suspensión se considera gravemente dañada',
	'Suspension height': 'Altura de la suspensión',
	'Suspension set': 'Conjunto de suspensión',
	'Suspension stiffness': 'Rigidez de la suspensión',
	'Suspension strength': 'Rigidez de la suspensión',
	'Suspensions': 'Suspensiones',
	'Texts': 'Textos del juego',
	'The amount of fuel in the addon': 'Cantidad de combustible que almacena el complemento',
	'The amount of permissible damage to the gas tank': 'Daño que puede soportar el depósito de combustible',
	'The amount of possible damage to the engine': 'Daño total que puede soportar el motor',
	'The amount of possible damage to the gearbox': 'Daño total que puede soportar la caja de cambios',
	'The amount of possible damage to the suspension': 'Daño total que puede soportar la suspensión',
	'The amount of water in the addon': 'Cantidad de agua que almacena el complemento',
	'The angle of inclination of the wheel in the direction of rotation': 'Ángulo de inclinación de la rueda en la dirección de giro',
	'The basic fuel consumption of the engine': 'Consumo base de combustible del motor',
	'The coefficient of change in fuel consumption when using all-wheel drive': 'Multiplicador del consumo al activar la tracción total',
	'The coefficient of increase in suspension damage with a punctured wheel': 'Multiplicador del daño de suspensión cuando una rueda está pinchada',
	'The cost of the item / truck in the store. In the case of a truck, this is only the basic cost, which does not include the cost of standard equipment when purchased in a store': 'Precio base del objeto o camión en la tienda. En los camiones no incluye el equipamiento que viene instalado al comprarlo.',
	'The damage threshold, after which the box begins to show signs of failure - flying gears and increased fuel consumption': 'Nivel de daño a partir del cual la caja empieza a fallar, pierde marchas y aumenta el consumo',
	'The export path is not specified.': 'No se indicó dónde guardar la exportación.',
	'The file for import is not selected.': 'No se seleccionó ningún archivo para importar.',
	'The following files have been merged into one:': 'Los siguientes archivos se combinaron en uno:',
	'The initial.pak backup was saved successfully.': 'La copia de seguridad de initial.pak se guardó correctamente.',
	'The limiter of the maximum angular acceleration of the wheels. The smaller it is, the slower the car accelerates': 'Limita la aceleración angular máxima de las ruedas. Cuanto menor sea el valor, más despacio acelerará el vehículo.',
	'The list is empty': 'No hay elementos que coincidan con los filtros',
	'The maximum angle of rotation of the wheel when taxiing': 'Ángulo máximo de giro de la rueda al dirigir el vehículo',
	'The maximum angular velocity of the wheel in this gear': 'Velocidad angular máxima que alcanza la rueda en esta marcha',
	'The maximum frequency of transmission failure, at the moment when the strength is approaching zero': 'Frecuencia máxima de fallos cuando la resistencia de la caja se acerca a cero',
	'The maximum fuel consumption multiplier, the consumption comes to this multiplier when the box is completely broken': 'Multiplicador máximo del consumo cuando la caja de cambios está completamente averiada',
	'The maximum stroke of a broken suspension': 'Recorrido máximo de una suspensión averiada',
	'The maximum value of the flow rate change in case of engine failure': 'Aumento máximo del consumo cuando el motor está averiado',
	'The minimum frequency of transmission failure, at the moment when the strength has reached a critical threshold': 'Frecuencia mínima de fallos cuando la caja alcanza el umbral de daño crítico',
	'The modification files could not be saved. There is no write access to the file.': 'No se pudieron guardar los archivos de la modificación porque no permiten escritura.',
	'The number of repair parts in the addon': 'Cantidad de puntos de reparación que contiene el complemento',
	'The number of repair wheels in the addon': 'Cantidad de ruedas de repuesto que contiene el complemento',
	'The parameters are exported.': 'Los parámetros se exportaron correctamente.',
	'The parameters are imported. Don\'t forget to save the changes!': '¡Los parámetros se importaron! Recuerda guardar los cambios.',
	'The program settings from the previous version have been detected. Do you want to use them?': 'Se encontraron ajustes de una versión anterior. ¿Quieres conservarlos?',
	'The purchased DLC with the KRS 58 Bandit car is required for use.': 'Esta opción requiere el DLC que incluye el KRS 58 Bandit.',
	'The region where the car is available for purchase': 'Región en la que el vehículo está disponible para comprar',
	'The speed at which the steering wheel returns to its original position after turning': 'Velocidad a la que la dirección vuelve al centro después de girar',
	'The threshold of critical failure. After this threshold, the fuel consumption and engine power change': 'Al superar este nivel de daño cambian el consumo y la potencia del motor',
	'This file contains the parameters of the following files:': 'Este archivo contiene los parámetros de:',
	'Tire': 'Neumático',
	'To add the mod, you need to restart the program. Perform a reboot?': 'Para aplicar el cambio de modificaciones hay que reiniciar la aplicación. ¿Reiniciar ahora?',
	'Torque': 'Par motor',
	'Trailer mass': 'Masa del remolque',
	'Trailers': 'Remolques',
	'Trucks': 'Vehículos',
	'Type of wheel drive': 'Tipo de tracción de la rueda',
	'Uninstall the program': 'Desinstalar la aplicación',
	'Uninstalled': 'No instalado',
	'Unlock': 'Desbloqueo y precio',
	'Unlock level': 'Rango de desbloqueo',
	'Unlock method': 'Método de desbloqueo',
	'Unpack archive': 'Volver a extraer archivos',
	'Unpacking': 'Extrayendo archivos',
	'Update': 'Actualizar',
	'Update archive': 'Guardar cambios en initial.pak',
	'Update the program': 'Buscar actualizaciones',
	'Upon reaching which level the item / truck opens. It is ignored if it is worth unlocking by exploration': 'Rango necesario para desbloquear el objeto o camión. Se ignora si se desbloquea al encontrarlo en el mapa.',
	'USA': 'Estados Unidos',
	'Useful content': 'Recursos del remolque',
	'Version': 'Versión y novedades',
	'Water': 'Agua',
	'Water capacity': 'Capacidad de agua',
	'What\'s new in the version': 'Novedades de la versión',
	'Wheel': 'Rueda',
	'Wheel repairs capacity': 'Ruedas de repuesto',
	'Wheel size': 'Tamaño de la rueda',
	'Wheel suspension height': 'Altura de la suspensión de esta rueda',
	'Wheel suspension stiffness': 'Rigidez de la suspensión de esta rueda',
	'Wheels': 'Ruedas',
	'Winch': 'Cabrestante',
	'Winch length': 'Longitud del cabrestante',
	'Winch strength': 'Fuerza del cabrestante',
	'Winches': 'Cabrestantes',
	'Works from': 'Funciona con el motor apagado',
	'Yellow zone: {}': 'Zona amarilla: {}',
	'Yes': 'Sí',
	'You didn\'t select a folder!': 'No seleccionaste ninguna carpeta.',
	'You have selected the wrong folder!': 'La carpeta seleccionada no contiene los archivos esperados.',
	'YouTube(RU)': 'YouTube del proyecto original (ruso)'
}

/** Traduce un valor heredado cuando existe una equivalencia española. */
export function translateToSpanish<T>(value: T): T {
	if (typeof value !== 'string') {
		return value
	}

	return (SPANISH_TRANSLATIONS[value] ?? value) as T
}
